services:
  vue-app:
    build: ./front-app/text-generation
    ports:
      - "8001:80"
    volumes:
      - ./front-app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production

  app:
    build: ./core-app
    container_name: data-generation-service
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./core-app:/app

    restart: unless-stopped
    depends_on:
      postgres: 
        condition: service_healthy

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 1s
      retries: 10

volumes:
  postgres_data:
