version: '3'
services:
  vue-app:
    build: .
    ports:
      - "8001:80"
    volumes:
      - ./dist:/usr/share/nginx/html  # монтируем только готовую сборку
    environment:
      - NODE_ENV=production
